version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: telecom_feature_store
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-telecom_churn}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
      - scraped_storage:/data

  python_pipeline:
    build: . # <--- Tells docker-compose to build your new custom Dockerfile locally
    container_name: churn_python_env
    volumes:
      - scraped_storage:/data
      - .:/app
    working_dir: /app
    tty: true

volumes:
  pgdata:
  n8n_data:
  scraped_storage: